version: '3'
services:
  postgres:
    image: postgres:9.6.9-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: supersecret

  kong_migrations:
    image: kong:0.14.0-alpine
    restart: on-failure
    command:
      - kong
      - migrations
      - up
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: postgres
      KONG_PG_DATABASE: postgres
      KONG_PG_PASSWORD: supersecret
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stdout
    depends_on: 
      - postgres

  kong:
    image: kong:0.14.0-alpine
    container_name: kong
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: supersecret
      KONG_PG_DATABASE: postgres
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    depends_on: 
      - postgres
      - kong_migrations
